-- TS.01
-- TC.01.00
INSERT INTO SSCIS.SSCIS_USER (LOGIN, CREATED, ACTIVATED, ID_ROLE, FIRSTNAME, LASTNAME, STUDENT_NUMBER) VALUES ('USER_TST_00', TO_DATE('01.01.2019','DD.MM.YYYY'), TO_DATE('01.01.2019','DD.MM.YYYY'), (SELECT ID FROM SSCIS.ENUM_ROLE WHERE ROLE = 'USER'), 'Jan', 'Novák', 'A16B0001P');

-- TC.01.01

-- TC.01.02
INSERT INTO SSCIS.SSCIS_USER (LOGIN, CREATED, ACTIVATED, ID_ROLE) VALUES ('USER_TST_01', SYSDATE, SYSDATE, (SELECT ID FROM SSCIS.ENUM_ROLE WHERE ROLE = 'USER'));

-- TC.01.03
INSERT INTO SSCIS.SSCIS_USER (LOGIN, CREATED, ACTIVATED, ID_ROLE) VALUES ('ADMIN_TST_00', SYSDATE, SYSDATE, (SELECT ID FROM SSCIS.ENUM_ROLE WHERE ROLE = 'ADMIN'));

COMMIT;
