-- Odstraneni rekurzivnich vazeb
UPDATE SSCIS.ENUM_SUBJECT SET ID_PARENT = NULL;

-- Smazani obsahu tabulky ENUM_SUBJECT
DELETE SSCIS.ENUM_SUBJECT;

-- Naplneni tabulky ENUM_SUBJECT predmety
INSERT INTO SSCIS.ENUM_SUBJECT (ID, CODE, NAME, LESSON, ID_PARENT) VALUES (1, 'INF', 'Informatika', 1, NULL);
INSERT INTO SSCIS.ENUM_SUBJECT (ID, CODE, NAME, LESSON, ID_PARENT) VALUES (2, 'MAT', 'Matematika', 1, NULL);
INSERT INTO SSCIS.ENUM_SUBJECT (ID, CODE, NAME, LESSON, ID_PARENT) VALUES (3, 'MECH', 'Mechanika', 1, NULL);

INSERT INTO SSCIS.ENUM_SUBJECT (ID, CODE, NAME, LESSON, ID_PARENT) VALUES (4, 'KMA/M1', 'Matematika 1', 0, 2);
INSERT INTO SSCIS.ENUM_SUBJECT (ID, CODE, NAME, LESSON, ID_PARENT) VALUES (5, 'KMA/M2', 'Matematika 2', 0, 2);
INSERT INTO SSCIS.ENUM_SUBJECT (ID, CODE, NAME, LESSON, ID_PARENT) VALUES (6, 'KMA/MA1', 'Matematická analýza 1', 0, 2);
INSERT INTO SSCIS.ENUM_SUBJECT (ID, CODE, NAME, LESSON, ID_PARENT) VALUES (7, 'KMA/MA2', 'Matematická analýza 2', 0, 2);
INSERT INTO SSCIS.ENUM_SUBJECT (ID, CODE, NAME, LESSON, ID_PARENT) VALUES (8, 'KIV/PPA1', 'Počítače a programování 1', 0, 1);
INSERT INTO SSCIS.ENUM_SUBJECT (ID, CODE, NAME, LESSON, ID_PARENT) VALUES (9, 'KIV/PPA2', 'Počítače a programování 2', 0, 1);
INSERT INTO SSCIS.ENUM_SUBJECT (ID, CODE, NAME, LESSON, ID_PARENT) VALUES (10, 'KMA/LAA', 'Lineární algebra', 0, 2);
INSERT INTO SSCIS.ENUM_SUBJECT (ID, CODE, NAME, LESSON, ID_PARENT) VALUES (11, 'KMA/DMA', 'Diskrétní matematika', 0, 2);
INSERT INTO SSCIS.ENUM_SUBJECT (ID, CODE, NAME, LESSON, ID_PARENT) VALUES (12, 'KIV/UPG', 'Úvod do počítačové grafiky', 0, 1);
INSERT INTO SSCIS.ENUM_SUBJECT (ID, CODE, NAME, LESSON, ID_PARENT) VALUES (13, 'KMA/M1S', 'Matematika 1', 0, 2);
INSERT INTO SSCIS.ENUM_SUBJECT (ID, CODE, NAME, LESSON, ID_PARENT) VALUES (14, 'KMA/M2S', 'Matematika 2', 0, 2);
INSERT INTO SSCIS.ENUM_SUBJECT (ID, CODE, NAME, LESSON, ID_PARENT) VALUES (15, 'KMA/MA1E', 'Matematika 1', 0, 2);
INSERT INTO SSCIS.ENUM_SUBJECT (ID, CODE, NAME, LESSON, ID_PARENT) VALUES (16, 'KMA/M2E', 'Matematika 2', 0, 2);
INSERT INTO SSCIS.ENUM_SUBJECT (ID, CODE, NAME, LESSON, ID_PARENT) VALUES (17, 'KMA/ZM2', 'Základy matematiky 2', 0, 2);
INSERT INTO SSCIS.ENUM_SUBJECT (ID, CODE, NAME, LESSON, ID_PARENT) VALUES (18, 'KME/UMM', 'Úvod do modelování v mechanice', 0, 3);

COMMIT;
