-- 00_CREATE_USER.sql
-- Vytvori TABLESPACE a uzivatele a prideli mu prava

CREATE TABLESPACE SSCIS_TABLESPACE
  DATAFILE 'SSCIS.dat' SIZE 10M
  AUTOEXTEND ON;
  
CREATE TEMPORARY TABLESPACE SSCIS_TABLESPACE_TMP
  TEMPFILE 'SSCIS_TMP.dat' SIZE 5M
  AUTOEXTEND ON;
  
CREATE USER SSCIS
  IDENTIFIED BY password
  DEFAULT TABLESPACE SSCIS_TABLESPACE
  TEMPORARY TABLESPACE SSCIS_TABLESPACE_TMP;
  
GRANT CREATE SESSION TO SSCIS;
GRANT CREATE TABLE TO SSCIS;
GRANT UNLIMITED TABLESPACE TO SSCIS;