-- 01_CREATE_TABLES.sql
-- Vytvori zakladni tabulky

-- Tabulka systemovych parametru
CREATE TABLE SSCIS.SSCIS_PARAM (
  ID NUMBER(10) NOT NULL,
  PARAM_KEY VARCHAR2(30 CHAR) NOT NULL,
  PARAM_VALUE  VARCHAR2(60 CHAR) NOT NULL,
  DESCRIPTION  VARCHAR2(120 CHAR),
  CONSTRAINT SSCIS_PARAM_PK PRIMARY KEY (ID)
);


-- Tabulka uzivatelu
CREATE TABLE SSCIS.SSCIS_USER (
    ID              NUMBER(10),
    LOGIN           VARCHAR2(40 CHAR) NOT NULL,
    FIRSTNAME       VARCHAR2(40 CHAR),
    LASTNAME        VARCHAR2(40 CHAR),
    PASSWORD        VARCHAR2(40 CHAR),
    ID_ROLE         NUMBER(10),
    IS_ACTIVE       NUMBER(1),
    CREATED         DATE,
    ACTIVATED       DATE,
    ID_ACTIVATED_BY NUMBER(10),
    STUDENT_NUMBER  VARCHAR2(20 CHAR),

    CONSTRAINT SSCIS_USER_PK PRIMARY KEY (ID)
);


-- Tabulka rozvrhovych akci
CREATE TABLE SSCIS.EVENT (
    ID                  NUMBER(10),
    TIME_FROM           DATE NOT NULL,
    TIME_TO             DATE NOT NULL,
    ID_SUBJECT          NUMBER(10) NOT NULL,
    ID_TUTOR            NUMBER(10) NOT NULL,
    IS_ACCEPTED         NUMBER(1),
    IS_CANCELLED        NUMBER(1),
    CANCELATION_COMMENT VARCHAR2(120 CHAR),

    CONSTRAINT EVENT_PK PRIMARY KEY (ID)
);


-- Tabulka zadosti a tutora
CREATE TABLE SSCIS.TUTOR_APPLICATION (
    ID               NUMBER(10),
    ID_USER          NUMBER(10) NOT NULL,
    APPLICATION_DATE DATE NOT NULL,
    IS_ACCEPTED      NUMBER(1),
    ACCEPTED_DATE    DATE,
    ACCEPTED_BY_ID   NUMBER(10),

    CONSTRAINT TUTOR_APPLICATION_PK PRIMARY KEY (ID)
);


-- Tabulka predmetu zadosti o tutora
CREATE TABLE SSCIS.TUTOR_APPLICATION_SUBJECT (
    ID             NUMBER(10),
    ID_SUBJECT     NUMBER(10) NOT NULL,
    ID_APPLICATION NUMBER(10) NOT NULL,
    DEGREE         NUMBER(1),

    CONSTRAINT TUTOR_APPLICATION_SUBJECT_PK PRIMARY KEY (ID)
);


-- Tabulka aprobaci pro doucovani predmetu
CREATE TABLE SSCIS.APPROVAL (
    ID         NUMBER(10),
    ID_TUTOR   NUMBER(10) NOT NULL,
    ID_SUBJECT NUMBER(10) NOT NULL,

    CONSTRAINT APPROVAL_PK PRIMARY KEY (ID)
);


-- Tabulka editovatelneho obsahu
CREATE TABLE SSCIS.SSCIS_CONTENT (
    ID           NUMBER(10),
    ID_AUTHOR    NUMBER(10) NOT NULL,
    ID_EDITED_BY NUMBER(10),
    CREATED      DATE NOT NULL,
    EDITED       DATE,
    TEXT_CONTENT VARCHAR2(800 CHAR),

    CONSTRAINT CONTENT_PK PRIMARY KEY (ID)
);


-- Tabulka session
CREATE TABLE SSCIS.SSCIS_SESSION (
    ID            NUMBER(10),
    ID_USER       NUMBER(10) NOT NULL,
    SESSION_START DATE NOT NULL,
    EXPIRATION    DATE NOT NULL,
    HASH          VARCHAR2(120 CHAR) NOT NULL,

    CONSTRAINT SSCIS_SESSION_PK PRIMARY KEY (ID)
);


-- Cieslnik roli
CREATE TABLE SSCIS.ENUM_ROLE (
    ID          NUMBER(10),
    ROLE        VARCHAR2(6 CHAR) NOT NULL,
    DESCRIPTION VARCHAR2(30 CHAR),

    CONSTRAINT ENUM_ROLE_PK PRIMARY KEY (ID)
);


-- Ciselnik predmetu
CREATE TABLE SSCIS.ENUM_SUBJECT (
    ID   NUMBER(10),
    CODE VARCHAR2(10 CHAR) NOT NULL,
    NAME VARCHAR2(30 CHAR),

    CONSTRAINT ENUM_SUBJECT_ID PRIMARY KEY (ID)
);