-- 01_CREATE_TABLES.sql
-- Vytvori zakladni tabulky

-- Tabulka systemovych parametru vcetne seqence a triggeru
CREATE TABLE SSCIS.SSCIS_PARAM (
  ID NUMBER(10) NOT NULL,
  PARAM_KEY VARCHAR2(30 CHAR) NOT NULL,
  PARAM_VALUE  VARCHAR2(60 CHAR) NOT NULL,
  
  CONSTRAINT SSCIS_PARAM _PK PRIMARY KEY (ID)
);

CREATE SEQUENCE SSCIS.SSCIS_PARAM_SEQ 
  START WITH 1
  INCREMENT BY 1;

CREATE TRIGGER SSCIS.SSCIS_PARAM_TRIGGER
  BEFORE INSERT ON SSCIS.SSCIS_PARAM
  FOR EACH ROW
    WHEN (new.ID IS NULL)
  BEGIN 
    SELECT SSCIS.SSCIS_PARAM_SEQ.NEXTVAL
    INTO :new.ID
    FROM DUAL;
  END;
/