-- 04_CREATE_TRIGERS.sql
-- Vytvori triggery pro vkladani do tabulek, ktere dosadi hodnotu s prislusne sekvence jako ID

CREATE TRIGGER SSCIS.SSCIS_PARAM_TRIGGER
  BEFORE INSERT ON SSCIS.SSCIS_PARAM
  FOR EACH ROW
    WHEN (new.ID IS NULL)
  BEGIN 
    SELECT SSCIS.SSCIS_PARAM_SEQ.NEXTVAL
    INTO :new.ID
    FROM DUAL;
  END;
/

CREATE TRIGGER SSCIS.SSCIS_USER_TRIGGER
  BEFORE INSERT ON SSCIS.SSCIS_USER
  FOR EACH ROW
    WHEN (new.ID IS NULL)
  BEGIN 
    SELECT SSCIS.SSCIS_USER_SEQ.NEXTVAL
    INTO :new.ID
    FROM DUAL;
  END;
/

CREATE TRIGGER SSCIS.EVENT_TRIGGER
  BEFORE INSERT ON SSCIS.EVENT
  FOR EACH ROW
    WHEN (new.ID IS NULL)
  BEGIN 
    SELECT SSCIS.EVENT_SEQ.NEXTVAL
    INTO :new.ID
    FROM DUAL;
  END;
/

CREATE TRIGGER SSCIS.TUTOR_APPLICATION_TRIGGER
  BEFORE INSERT ON SSCIS.TUTOR_APPLICATION
  FOR EACH ROW
    WHEN (new.ID IS NULL)
  BEGIN 
    SELECT SSCIS.TUTOR_APPLICATION_SEQ.NEXTVAL
    INTO :new.ID
    FROM DUAL;
  END;
/

CREATE TRIGGER SSCIS.TUTOR_APP_SUBJECT_TRIGGER
  BEFORE INSERT ON SSCIS.TUTOR_APPLICATION_SUBJECT
  FOR EACH ROW
    WHEN (new.ID IS NULL)
  BEGIN 
    SELECT SSCIS.TUTOR_APPLICATION_SUBJECT_SEQ.NEXTVAL
    INTO :new.ID
    FROM DUAL;
  END;
/

CREATE TRIGGER SSCIS.APPROVAL_TRIGGER
  BEFORE INSERT ON SSCIS.APPROVAL
  FOR EACH ROW
    WHEN (new.ID IS NULL)
  BEGIN 
    SELECT SSCIS.APPROVAL_SEQ.NEXTVAL
    INTO :new.ID
    FROM DUAL;
  END;
/

CREATE TRIGGER SSCIS.SSCIS_CONTENT_TRIGGER
  BEFORE INSERT ON SSCIS.SSCIS_CONTENT
  FOR EACH ROW
    WHEN (new.ID IS NULL)
  BEGIN 
    SELECT SSCIS.SSCIS_CONTENT_SEQ.NEXTVAL
    INTO :new.ID
    FROM DUAL;
  END;
/

CREATE TRIGGER SSCIS.SSCIS_SESSION_TRIGGER
  BEFORE INSERT ON SSCIS.SSCIS_SESSION
  FOR EACH ROW
    WHEN (new.ID IS NULL)
  BEGIN 
    SELECT SSCIS.SSCIS_SESSION_SEQ.NEXTVAL
    INTO :new.ID
    FROM DUAL;
  END;
/

CREATE TRIGGER SSCIS.ENUM_ROLE_TRIGGER
  BEFORE INSERT ON SSCIS.ENUM_ROLE
  FOR EACH ROW
    WHEN (new.ID IS NULL)
  BEGIN 
    SELECT SSCIS.ENUM_ROLE_SEQ.NEXTVAL
    INTO :new.ID
    FROM DUAL;
  END;
/

CREATE TRIGGER SSCIS.ENUM_SUBJECT_TRIGGER
  BEFORE INSERT ON SSCIS.ENUM_SUBJECT
  FOR EACH ROW
    WHEN (new.ID IS NULL)
  BEGIN 
    SELECT SSCIS.ENUM_SUBJECT_SEQ.NEXTVAL
    INTO :new.ID
    FROM DUAL;
  END;
/

CREATE TRIGGER SSCIS.PARTICIPATION_TRIGGER
  BEFORE INSERT ON SSCIS.PARTICIPATION
  FOR EACH ROW
    WHEN (new.ID IS NULL)
  BEGIN
    SELECT SSCIS.PARTICIPATION_SEQ.NEXTVAL
    INTO :new.ID
    FROM DUAL;
  END;
/

CREATE TRIGGER SSCIS.FEEDBACK_TRIGGER
  BEFORE INSERT ON SSCIS.FEEDBACK
  FOR EACH ROW
    WHEN (new.ID IS NULL)
  BEGIN
    SELECT SSCIS.FEEDBACK_SEQ.NEXTVAL
    INTO :new.ID
    FROM DUAL;
  END;
/