-- 04_FOREIGN_KEYS.sql
-- Vytvori cizi klice mezi tabulkami

-- SSCIS.APPROVAL
ALTER TABLE SSCIS.APPROVAL
ADD CONSTRAINT FK_APPROVAL_TUTOR
  FOREIGN KEY (ID_TUTOR)
  REFERENCES SSCIS.SSCIS_USER(ID);
  
ALTER TABLE SSCIS.APPROVAL
ADD CONSTRAINT FK_APPROVAL_SUBJECT
  FOREIGN KEY (ID_SUBJECT)
  REFERENCES SSCIS.ENUM_SUBJECT(ID);
  
-- SSCIS.EVENT
ALTER TABLE SSCIS.EVENT
ADD CONSTRAINT FK_EVENT_SUBJECT
  FOREIGN KEY (ID_SUBJECT)
  REFERENCES SSCIS.ENUM_SUBJECT(ID);
  
ALTER TABLE SSCIS.EVENT
ADD CONSTRAINT FK_EVENT_TUTOR
  FOREIGN KEY (ID_TUTOR)
  REFERENCES SSCIS.SSCIS_USER(ID);
  
-- SSCIS.SSCIS_CONTENT
ALTER TABLE SSCIS.SSCIS_CONTENT
ADD CONSTRAINT FK_SSCIS_CONTENT_AUTHOR
  FOREIGN KEY (ID_AUTHOR)
  REFERENCES SSCIS.SSCIS_USER(ID);
  
ALTER TABLE SSCIS.SSCIS_CONTENT
ADD CONSTRAINT FK_SSCIS_CONTENT_EDITOR
  FOREIGN KEY (ID_EDITED_BY)
  REFERENCES SSCIS.SSCIS_USER(ID);
  
-- SSCIS.SSCIS_SESSION
ALTER TABLE SSCIS.SSCIS_SESSION
ADD CONSTRAINT FK_SSCIS_SESSION_USER
  FOREIGN KEY (ID_USER)
  REFERENCES SSCIS.SSCIS_USER(ID);
  
-- SSCIS.SSCIS_USER
ALTER TABLE SSCIS.SSCIS_USER
ADD CONSTRAINT FK_SSCIS_USER_ROLE
  FOREIGN KEY (ID_ROLE)
  REFERENCES SSCIS.ENUM_ROLE(ID);
  
ALTER TABLE SSCIS.SSCIS_USER
ADD CONSTRAINT FK_SSCIS_USER_ACTBY
  FOREIGN KEY (ID_ACTIVATED_BY)
  REFERENCES SSCIS.SSCIS_USER(ID);

-- SSCIS.TUTOR_APPLICATION
ALTER TABLE SSCIS.TUTOR_APPLICATION
ADD CONSTRAINT FK_TUTAPP_USER
  FOREIGN KEY (ID_USER)
  REFERENCES SSCIS.SSCIS_USER(ID);
  
ALTER TABLE SSCIS.TUTOR_APPLICATION
ADD CONSTRAINT FK_TUTAPP_ACCBY
  FOREIGN KEY (ACCEPTED_BY_ID)
  REFERENCES SSCIS.SSCIS_USER(ID);

-- SSCIS.TUTOR_APPLICATION_SUBJECT
ALTER TABLE SSCIS.TUTOR_APPLICATION_SUBJECT
ADD CONSTRAINT FK_TUTAPPSUB_SUBJECT
  FOREIGN KEY (ID_SUBJECT)
  REFERENCES SSCIS.ENUM_SUBJECT(ID);
  
ALTER TABLE SSCIS.TUTOR_APPLICATION_SUBJECT
ADD CONSTRAINT FK_TUTAPPSUB_APPLICATION
  FOREIGN KEY (ID_APPLICATION)
  REFERENCES SSCIS.TUTOR_APPLICATION(ID);
  
-- SSCIS.PARTICIPATION
ALTER TABLE SSCIS.PARTICIPATION
ADD CONSTRAINT FK_PARTICIP_SUSER
  FOREIGN KEY (ID_USER)
  REFERENCES SSCIS.SSCIS_USER(ID);
  
ALTER TABLE SSCIS.PARTICIPATION
ADD CONSTRAINT FK_PATICIP_EVENT
  FOREIGN KEY (ID_EVENT)
  REFERENCES SSCIS.EVENT(ID);
  
-- SSCIS.FEEDBACK
ALTER TABLE SSCIS.FEEDBACK
ADD CONSTRAINT FK_FEEDBACK_PARTICIP
  FOREIGN KEY (ID_PARTICIPATION)
  REFERENCES SSCIS.PARTICIPATION(ID);