INSERT INTO SSCIS.SSCISPARAM (PARAM_KEY, PARAM_VALUE, DESCRIPTION) VALUES ('SESSION_LENGTH', '900', 'Delka session v sekundach');
INSERT INTO SSCIS.SSCISPARAM (PARAM_KEY, PARAM_VALUE, DESCRIPTION) VALUES ('VERSION', '0.0.0', 'Oznaceni verze');
COMMIT;