//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSCISResources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SSCISResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Přidat předmět.
        /// </summary>
        public static string ADD_SUBJECT
        {
            get
            {
                return ResourceManager.GetString("ADD_SUBJECT", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Student Support Centre.
        /// </summary>
        public static string APPLICATION_NAME
        {
            get
            {
                return ResourceManager.GetString("APPLICATION_NAME", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Autor.
        /// </summary>
        public static string AUTHOR
        {
            get
            {
                return ResourceManager.GetString("AUTHOR", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Zpět.
        /// </summary>
        public static string BACK
        {
            get
            {
                return ResourceManager.GetString("BACK", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Obsah.
        /// </summary>
        public static string CONTENT
        {
            get
            {
                return ResourceManager.GetString("CONTENT", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Opravdu chcete smazat tento obsah?.
        /// </summary>
        public static string CONTENT_DELETE_CONFIRM
        {
            get
            {
                return ResourceManager.GetString("CONTENT_DELETE_CONFIRM", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Vytvořit.
        /// </summary>
        public static string CREATE
        {
            get
            {
                return ResourceManager.GetString("CREATE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Vytvořit novinku.
        /// </summary>
        public static string CREATE_NEWS
        {
            get
            {
                return ResourceManager.GetString("CREATE_NEWS", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Vytvořit rozvrhovou akci.
        /// </summary>
        public static string CREATE_SCHEDULE_EVENT
        {
            get
            {
                return ResourceManager.GetString("CREATE_SCHEDULE_EVENT", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Vytvořeno.
        /// </summary>
        public static string CREATED
        {
            get
            {
                return ResourceManager.GetString("CREATED", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Známka.
        /// </summary>
        public static string DEGREE
        {
            get
            {
                return ResourceManager.GetString("DEGREE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Smazat.
        /// </summary>
        public static string DELETE
        {
            get
            {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string DETAIL
        {
            get
            {
                return ResourceManager.GetString("DETAIL", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Upravit.
        /// </summary>
        public static string EDIT
        {
            get
            {
                return ResourceManager.GetString("EDIT", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Upravit novinku.
        /// </summary>
        public static string EDIT_NEWS
        {
            get
            {
                return ResourceManager.GetString("EDIT_NEWS", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Upraveno.
        /// </summary>
        public static string EDITED
        {
            get
            {
                return ResourceManager.GetString("EDITED", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Upraveno uživatelem.
        /// </summary>
        public static string EDITED_BY
        {
            get
            {
                return ResourceManager.GetString("EDITED_BY", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nadpis.
        /// </summary>
        public static string HEADER
        {
            get
            {
                return ResourceManager.GetString("HEADER", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Domů.
        /// </summary>
        public static string HOME
        {
            get
            {
                return ResourceManager.GetString("HOME", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Píjmení.
        /// </summary>
        public static string LASTNAME
        {
            get
            {
                return ResourceManager.GetString("LASTNAME", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LOGIN
        {
            get
            {
                return ResourceManager.GetString("LOGIN", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Jméno.
        /// </summary>
        public static string NAME
        {
            get
            {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Novinky.
        /// </summary>
        public static string NEWS
        {
            get
            {
                return ResourceManager.GetString("NEWS", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Uložit.
        /// </summary>
        public static string SAVE
        {
            get
            {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Předmět.
        /// </summary>
        public static string SUBJECT
        {
            get
            {
                return ResourceManager.GetString("SUBJECT", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Předměty.
        /// </summary>
        public static string SUBJECTS
        {
            get
            {
                return ResourceManager.GetString("SUBJECTS", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Správa předmětů.
        /// </summary>
        public static string SUBJECTS_MANAGEMENT
        {
            get
            {
                return ResourceManager.GetString("SUBJECTS_MANAGEMENT", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Systémové parametry.
        /// </summary>
        public static string SYSTEM_PARAMS
        {
            get
            {
                return ResourceManager.GetString("SYSTEM_PARAMS", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rozvrh po přihlášení.
        /// </summary>
        public static string TIMETABLE_AFTER_LOGIN
        {
            get
            {
                return ResourceManager.GetString("TIMETABLE_AFTER_LOGIN", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Přihláška tutora.
        /// </summary>
        public static string TUTOR_APPLICATION
        {
            get
            {
                return ResourceManager.GetString("TUTOR_APPLICATION", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Příhlášky tutorů.
        /// </summary>
        public static string TUTOR_APPLICATIONS
        {
            get
            {
                return ResourceManager.GetString("TUTOR_APPLICATIONS", resourceCulture);
            }
        }
    }
}
