//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSCIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSCISContent
    {
        public int ID { get; set; }
        public int AuthorID { get; set; }
        public Nullable<int> EditedByID { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Edited { get; set; }
        public string TextContent { get; set; }
        public string Header { get; set; }
    
        public virtual SSCISUser Author { get; set; }
        public virtual SSCISUser EditedBy { get; set; }
    }
}
