//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSCIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSCISParam
    {
        public int ID { get; set; }
        public string ParamKey { get; set; }
        public string ParamValue { get; set; }
        public string Description { get; set; }
    }
}
