//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSCIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TutorApplication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TutorApplication()
        {
            this.Subjects = new HashSet<TutorApplicationSubject>();
        }
    
        public int ID { get; set; }
        public int UserID { get; set; }
        public System.DateTime ApplicationDate { get; set; }
        public Nullable<bool> IsAccepted { get; set; }
        public Nullable<System.DateTime> AcceptedDate { get; set; }
        public Nullable<int> AcceptedByID { get; set; }
    
        public virtual SSCISUser AcceptedBy { get; set; }
        public virtual SSCISUser Applicant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TutorApplicationSubject> Subjects { get; set; }
    }
}
