//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSCIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TutorApplicationSubject
    {
        public int ID { get; set; }
        public int SubjectID { get; set; }
        public int ApplicationID { get; set; }
        public Nullable<bool> Degree { get; set; }
    
        public virtual Subject Subject { get; set; }
        public virtual TutorApplication TutorApplication { get; set; }
    }
}
